### ISSUE TITLE
GPU memory needed for trainig 

### ISSUE THREAD

**Issue by abdo-eldesokey** [visinf/irr#16]
Hi,
I was just wondering, how much GPU memory is needed for training?
I tried to train on KITTI with a batch size of 1 on a 16 GB GPU and I got out-of-memory error!
Thank you.

**Comment by hurjunhwa** [comment]
Hi,
Sorry for the late reply.
Have you found the solution? I remember that it costs around 15GB for finetuning on KITTI with a batch size of 4.
Thanks.

**Comment by abdo-eldesokey** [comment]
Hi,
It was dependencies problem that was causing the out of memory error. I downgraded PyTorch and Cuda and it works now with a batch size of 8 on FlyingChairs.
Thank you.
